server:
  port: 8083


spring:
  application:
    name: springcloud-service-music
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1x79bp89k930d62ho.mysql.rds.aliyuncs.com:3306/music_recommand?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: db_user0
    password: "Zxr123456"

logging:
  level:
    com:
      music:
        mapper: debug

mybatis:
  mapper-locations: com/music/mapper/*.xml
  type-aliases-package: com/music/entity

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka

  