server:
  port: 9000

spring:
  application:
    name: springcloud-consumer-user-feign

eureka:
  client:
    service-url:
      defaultZone: http://eureka8761:8761/eureka,http://eureka8762:8762/eureka

feign:
  hystrix:
    enabled: false


ribbon:
  # 饥饿加载
  eager-load:
    # 是否开启饥饿加载
    enabled: true
    # 饥饿加载的服务
    clients: springcloud-service-user,